### ISSUE TITLE
Brighten/Darken don't keep the original colors around

### ISSUE THREAD

**Issue by riknoll** [jwunderl/pxt-color#3]
When you apply the brighten and darken screen effects, they are destructive.

That is, if you call brighten a few times and then call darken the same number of times, the colors you have at the end will be different than your original palette.

Here's an example that illustrates the problem:

https://makecode.com/_Yi21CVPomh31

**Comment by jwunderl** [comment]
Hmm I fixed this because it seemed fun enough to try, change is a bit messy: https://github.com/jwunderl/pxt-color/compare/5dd5092...44f9db0 so I probably won't bump until I look it over again one more time.

Here's my test file with it fixed though https://makecode.com/_DVehjH0FoWPX there's likely a bit of a race condition if you spam a+b interleaved a bunch as I need to keep around the effects while it is 'reverting' in order for it to be stoppable / clearable; I'll probably add a bit more state for 'isCurrentlyBeingReverted' / etc and skip past those before I push a new version, but it's an edge case / I can't imagine most uses would hit it~

**Comment by tuna-ep** [comment]
@jwunderl I think I've spotted the problem with darken/brighten - `brightenEffect` changes the luminosity and saturation, but `darkenEffect` is changing luminosity twice. I think `darkenEffect` should look like this
```
    function darkenEffect() {
        const f = new Fade();
        return f.mapEndHSL(hsl => {
            hsl.luminosity *= .75;
            hsl.saturation *= .9;
            return hsl;
        });
    }
```

**Comment by jwunderl** [comment]
@tuna-ep You're right! Good catch. If you'd like to make a PR fixing that I'd be happy to merge it, otherwise I'll fix it next time I'm at my computer (I'm out of town at BETT london for another few days).

Thanks for taking a look / suggesting the fix!

**Comment by tuna-ep** [comment]
Just done that @jwunderl. btw thanks for creating this extension, I'm using it in my school project to switch between day and night.

**Comment by jwunderl** [comment]
fixed by @tuna-ep's pr https://github.com/jwunderl/pxt-color/pull/5

link from original post w/ updated extension version https://makecode.com/_0XKC071eAUW5
